config/routes.rb
Rails.application.routes.draw do
  get 'top/main'
  root 'top#main'
  resources :products
  resources :cart_items, only: [:new, :create, :destroy]
  resources :carts, only: [:show]
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/cart.rb
class Cart < ApplicationRecord
    has_many :cart_item
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
    belongs_to :product
    belongs_to :cart
end

app/models/product.rb
class Product < ApplicationRecord
    has_one :cart_item
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    helper_method :current_cart
    private
    def current_cart
        if session[:cart_id]
            cart = Cart.find(session[:cart_id])
        else
            cart = Cart.create
            session[:cart_id] = cart.id
        end
        cart
    end
end

app/controllers/cart_items_controller.rb
class CartItemsController < ApplicationController
  def new
    @cartitem = CartItem.new(product_id: params[:product_id])
  end

  def create
    @cartitem = CartItem.new(qty: params[:cart_item][:qty],
    product_id: params[:cart_item][:product_id], cart_id: current_cart.id)

    if @cartitem.save
      redirect_to root_path
    else
      render 'new'
    end
  end

  def destroy
    @cartitem = CartItem.find(params[:id])
    @cartitem.destroy
    redirect_to root_path
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def show
    @cartitems = CartItem.where(cart_id: current_cart.id)
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.all
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(name: params[:product][:name], price: params[:product][:price])
    if @product.save
      redirect_to products_path
    else
      render 'new'
    end
  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy
    redirect_to products_path
  end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def main
    redirect_to products_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/views/cart_items/create.html.erb
<h1>CartItems#create</h1>
<p>Find me in app/views/cart_items/create.html.erb</p>

app/views/cart_items/destroy.html.erb
<h1>CartItems#destroy</h1>
<p>Find me in app/views/cart_items/destroy.html.erb</p>

app/views/cart_items/new.html.erb
<h1>CartItems#new</h1>
<%= form_with model: @cartitem, local: true do |f| %>

  <%= Product.find(@cartitem.product_id).name %>
  <%= Product.find(@cartitem.product_id).price %>
  <%= f.label 'qty' %>
  <%= f.number_field :qty, in: 1..10, step: 1 %>


  <%= f.hidden_field :product_id %>
  <%= f.submit "購入" %>
<% end %>

app/views/carts/show.html.erb
<h1>Carts#show</h1>
<ul>
  <% @cartitems.each do |cart_item| %>
    <li>
      <%= Product.find(cart_item.product_id).name %>
      <%= Product.find(cart_item.product_id).price %>
      <%= cart_item.qty %>

      <%= button_to '削除', cart_item_path(cart_item), method: :delete, data: { confirm: '本当に削除しますか？' } %>
    </li>
  <% end %>
</ul>

<%= link_to '商品一覧', root_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>L6</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/products/index.html.erb
<h1>Products一覧</h1>
<ul>
<% @products.each do |p| %>
  <li>
    <%= p.name %>
    <%= p.price %>
    <%= link_to 'カート追加', new_cart_item_path(product_id: p.id)%>

    <%= button_to '削除', product_path(p), method: :delete, data: { confirm: '本当に削除しますか？' } %>
  </li>
<% end %>
<%= link_to '商品を追加する', new_product_path %>
<%= link_to 'カートを見る', cart_path(current_cart.id) %>

</ul>

app/views/products/new.html.erb
<h1>商品登録</h1>
<%= form_with model: @product, local: true do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :price %>
  <%= f.text_field :price %>

  <%= f.submit '作成' %>
<% end %>

app/views/top/main.html.erb
<h1>Top#main</h1>
<p>Find me in app/views/top/main.html.erb</p>